---
title: "openspecy1_20240530"
author: "Helen Lei"
date: "2024-05-30"
output: html_document
---

### Objectives
# try and summarize results by polymer_class, create a table
# organize by analyte type and station - how many samples do we have for different analytes from different locations


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


install.packages(c("plyr","dplyr","ggplot2","cowplot",
         "lubridate","tidyverse", "reshape2", 
         "ggExtra", "viridis", "rstatix", "stringr"))

lapply(c("plyr","dplyr","ggplot2","cowplot",
         "lubridate","tidyverse", "reshape2", 
         "ggExtra", "viridis", "rstatix", "stringr"), require, character.only=T)  

```

## Loading data

```{r}
##Check working directory so that you are in setwd("~/GitHub/CyanoSpatial/code")
getwd()

##Read in data
data <- read_csv("BigMeadow_March182022_1_100.csv")


#Viewing rows 6-11
subset_df <- data[6:11, ]
subset_df


#Setting row 6 as column names
colnames(subset_df) <- as.character(unlist(subset_df[1, ]))

#Removing the first row as it is now the header
subset_df <- subset_df[-1, ]

#Display
subset_df

#Giving columns 2 and 3 a name
names(subset_df)[2] <- "Particle #"
names(subset_df)[3] <- "Spectra #"

##Lessening the columns to reflect the information needed

sub <- subset_df[,c("Particle #", "Spectra #", "size W", "size L", "morphology", "color", "other observation", "match_val", "good_correlations", "plastic_or_not", "polymer_class")]


analyte_ecosystem <- group_by(ecosystems, Analyte, selected) %>% 
  summarise(group_size = n()) %>% 
  ungroup()


ecosystems[which(ecosystems$selected %in% c("Pond", "Lake", "River", "Slough", "Lagoon", "Creek", "Creek", "Mid-slough", "Bay", "Reservoir", "Estuary", "Dam")),] %>%
  group_by(selected) %>%
  count()

```

##Filtering the plastics

```{r pressure, echo=FALSE}

# Function to extract selected words from a string
extract_words <- function(input_text, words_to_extract) {cleaned_text <- str_replace_all(input_text, "[[:punct:]]", "")
  selected_words <- paste(words_to_extract[words_to_extract %in% strsplit(input_text, " ")[[1]]], collapse = " ")
  return(selected_words)
}

# Words you want to select and put in the new column
selected_words <- c("Dam", "Pond", "Lake", "Lake,", "River","River,", "Slough", "Lagoon", "Creek", "Creek,", "Mid-slough", "Bay", "Reservoir", "Estuary", "Channel", "Canal")

# Add a new column to the dataframe with the selected words
ecosystems <- sub %>%
  mutate(selected = sapply(StationName, extract_words, words_to_extract = selected_words))

# Making a new data frame with only the selected ecosystems and analyte
analyte_ecosystem <- group_by(ecosystems, Analyte, selected) %>% 
  summarise(group_size = n()) %>% 
  ungroup()


ecosystems[which(ecosystems$selected %in% c("Pond", "Lake", "River", "Slough", "Lagoon", "Creek", "Creek", "Mid-slough", "Bay", "Reservoir", "Estuary", "Dam")),] %>%
  group_by(selected) %>%
  count()

sum(analyte_ecosystem$group_size)


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
